# /.gitlab-ci.yml

image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - name: docker:19.03.1-dind

stages:
  - build
  - test

build:Linux_GCC_Build_Test_App:
  stage: build
  script:
  - sh docker_bash.sh "./git_clone_dependencies.sh && Test/Build_Tests/Linux_GCC_Build_Test_App/build.sh"

build:ARM_Cortex_M_GCC_Build_Test_App:
  stage: build
  script:
  - sh docker_bash.sh "./git_clone_dependencies.sh && Test/Build_Tests/ARM_Cortex_M_GCC_Build_Test_App/build.sh"

build:Unit_Test_Linux_App:
  stage: build
  script:
  - sh docker_bash.sh "./git_clone_dependencies.sh && Plat4m_Core/UnitTest/Unit_Test_Linux_App/build.sh"
  artifacts:
    paths:
      - Plat4m_Core/UnitTest/Unit_Test_Linux_App/Build/

build:Acceptance_Test_Linux_App:
  stage: build
  script:
  - sh docker_bash.sh "./git_clone_dependencies.sh && Test/Acceptance_Tests/Acceptance_Test_Linux_App/build.sh"
  artifacts:
    paths:
      - Test/Acceptance_Tests/Acceptance_Test_Linux_App/Build/
  
test:Unit_Test_Linux_App:
  stage: test
  script:
  - sh docker_bash.sh Plat4m_Core/UnitTest/Unit_Test_Linux_App/test.sh
  dependencies:
    - build:Unit_Test_Linux_App

test:Acceptance_Test_Linux_App:
  stage: test
  script:
  - sh docker_bash.sh Test/Acceptance_Tests/Acceptance_Test_Linux_App/test.sh
  dependencies:
    - build:Acceptance_Test_Linux_App
