# /.gitlab-ci.yml

image: bminerd/plat4m_linux_dev:1.1.0

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test

build:Linux_GCC_Build_Test_App:
  stage: build
  tags:
    - docker
  before_script:
  - ./git_clone_dependencies.sh
  - cd Test/Build_Tests/Linux_GCC_Build_Test_App
  script:
  - ./build.sh

build:ARM_Cortex_M_GCC_Build_Test_App:
  stage: build
  tags:
    - docker
  before_script:
  - ./git_clone_dependencies.sh
  - cd Test/Build_Tests/ARM_Cortex_M_GCC_Build_Test_App
  script:
  - ./build.sh

build:Unit_Test_Linux_App:
  stage: build
  tags:
    - docker
  before_script:
  - ./git_clone_dependencies.sh
  - cd Plat4m_Core/UnitTest/Unit_Test_Linux_App
  script:
  - ./build.sh
  artifacts:
    paths:
      - Plat4m_Core/UnitTest/Unit_Test_Linux_App/Build/

build:Acceptance_Test_Linux_App:
  stage: build
  tags:
    - docker
  before_script:
  - ./git_clone_dependencies.sh
  - cd Test/Acceptance_Tests/Acceptance_Test_Linux_App
  script:
  - ./build.sh
  artifacts:
    paths:
      - Test/Acceptance_Tests/Acceptance_Test_Linux_App/Build/

test:Unit_Test_Linux_App:
  stage: test
  tags:
    - docker
  before_script:
  - ./git_clone_dependencies.sh
  - cd Plat4m_Core/UnitTest/Unit_Test_Linux_App
  script:
  - ./test.sh
  dependencies:
    - build:Unit_Test_Linux_App

test:Acceptance_Test_Linux_App:
  stage: test
  tags:
    - docker
  before_script:
  - ./git_clone_dependencies.sh
  - cd Test/Acceptance_Tests/Acceptance_Test_Linux_App
  script:
  - ./test.sh
  dependencies:
    - build:Acceptance_Test_Linux_App
