title: Plat4m
description: Plat4m is a cross-platform C++ application framework designed for real-time systems running on anything from an 8-bit microcontroller to an x86 PC.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
