cmake_minimum_required (VERSION 3.0)

set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)

set(COMPILER_NAME "CLANG_LINUX" CACHE STRING "" FORCE)
set(COMPILER_PATH /usr)

set(CMAKE_C_COMPILER ${COMPILER_PATH}/bin/clang-12)
set(CMAKE_CXX_COMPILER ${COMPILER_PATH}/bin/clang++-12)
set(CMAKE_ASM_COMPILER ${COMPILER_PATH}/bin/clang-12)

set(COMPILER_FLAGS "-fno-limit-debug-info")

set(CMAKE_ASM_FLAGS ${COMPILER_FLAGS} CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS ${COMPILER_FLAGS} CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS ${COMPILER_FLAGS} CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS ${COMPILER_FLAGS} CACHE STRING "" FORCE)

# include_directories(${COMPILER_PATH}/arm-none-eabi/include)

# search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
